# Generated by Django 5.0.8 on 2024-09-16 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_subscriptionprice_timestamp_subscriptionprice_update_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionprice',
            options={'ordering': ['order', 'featured', '-update']},
        ),
    ]
